## Energy saved from recycling
<p>Did you know that recycling saves energy by reducing or eliminating the need to make materials from scratch? For example, aluminum can manufacturers can skip the energy-costly process of producing aluminum from ore by cleaning and melting recycled cans. Aluminum is classified as a non-ferrous metal.</p>
<p>Singapore has an ambitious goal of becoming a zero-waste nation. The amount of waste disposed of in Singapore has increased seven-fold over the last 40 years. At this rate, Semakau Landfill, Singaporeâ€™s only landfill, will run out of space by 2035. Making matters worse, Singapore has limited land for building new incineration plants or landfills.</p>
<p>The government would like to motivate citizens by sharing the total energy that the combined recycling efforts have saved every year. They have asked you to help them.</p>
<p>You have been provided with three datasets. The data come from different teams, so the names of waste types may differ.</p>
<div style="background-color: #efebe4; color: #05192d; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style="font-size:16px"><b>datasets/wastestats.csv - Recycling statistics per waste type for the period 2003 to 2017</b>
    </div>
    <div>Source: <a href="https://www.nea.gov.sg/our-services/waste-management/waste-statistics-and-overall-recycling">Singapore National Environment Agency</a></div>
<ul>
    <li><b>waste_type: </b>The type of waste recycled.</li>
    <li><b>waste_disposed_of_tonne: </b>The amount of waste that could not be recycled (in metric tonnes).</li>
    <li><b>total_waste_recycle_tonne: </b>The amount of waste that could be recycled (in metric tonnes).</li>
    <li><b>total_waste_generated: </b>The total amount of waste collected before recycling (in metric tonnes).</li>
    <li><b>recycling_rate: </b>The amount of waste recycled per tonne of waste generated.</li>
    <li><b>year: </b>The recycling year.</li>
</ul>
    </div>
<div style="background-color: #efebe4; color: #05192d; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6; margin-top: 17px;">
    <div style="font-size:16px"><b>datasets/2018_2019_waste.csv - Recycling statistics per waste type for the period 2018 to 2019</b>
    </div>
    <div> Source: <a href="https://www.nea.gov.sg/our-services/waste-management/waste-statistics-and-overall-recycling">Singapore National Environment Agency</a></div>
<ul>
    <li><b>Waste Type: </b>The type of waste recycled.</li>
    <li><b>Total Generated: </b>The total amount of waste collected before recycling (in thousands of metric tonnes).</li> 
    <li><b>Total Recycled: </b>The amount of waste that could be recycled. (in thousands of metric tonnes).</li>
    <li><b>Year: </b>The recycling year.</li>
</ul>
    </div>
<div style="background-color: #efebe4; color: #05192d; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6; margin-top: 17px;">
    <div style="font-size:16px"><b>datasets/energy_saved.csv -  Estimations of the amount of energy saved per waste type in kWh</b>
    </div>
<ul>
    <li><b>material: </b>The type of waste recycled.</li>
    <li><b>energy_saved: </b>An estimate of the energy saved (in kiloWatt hour) by recycling a metric tonne of waste.</li> 
    <li><b>crude_oil_saved: </b>An estimate of the number of barrels of oil saved by recycling a metric tonne of waste.</li>
</ul>

</div>
<pre><code>
</code></pre>

In [154]:
import pandas as pd

energy_saved = pd.read_csv("datasets/energy_saved.csv")
waste_03_17 = pd.read_csv('datasets/wastestats.csv')
waste_18_19 = pd.read_csv('datasets/2018_2019_waste.csv')

In [155]:
clean_waste_18_19 = waste_18_19.rename(
    columns={
        "Waste Type": "waste_type",
        "Total Generated ('000 tonnes)": "total_waste_generated_tonne",
        "Total Recycled ('000 tonnes)": "total_waste_recycled_tonne",
        "Year": "year",
    }
)
clean_waste_18_19["total_waste_generated_tonne"] = (
    clean_waste_18_19["total_waste_generated_tonne"] * 1000
)
clean_waste_18_19["total_waste_recycled_tonne"] = (
    clean_waste_18_19["total_waste_recycled_tonne"] * 1000
)

In [156]:
clean_waste_18_19["recycling_rate"] = round(
    clean_waste_18_19["total_waste_recycled_tonne"]
    / clean_waste_18_19["total_waste_generated_tonne"],
    2,
)

In [157]:
clean_energy_saved = (
    energy_saved.T.iloc[1:, 2:]
    .reset_index(drop=True)
    .rename(columns={2: "material", 3: "energy_saved", 4: "crude_oil_saved"})
)
clean_energy_saved = clean_energy_saved[["material","energy_saved"]]
clean_energy_saved = clean_energy_saved.drop(4, axis=0)
clean_energy_saved

            material energy_saved
0            Plastic     5774 Kwh
1              Glass       42 Kwh
2      Ferrous Metal      642 Kwh
3  Non-Ferrous Metal    14000 Kwh

In [158]:
clean_waste_03_17 = waste_03_17.loc[
    :,
    [
        "waste_type",
        "total_waste_generated_tonne",
        "total_waste_recycled_tonne",
        "recycling_rate",
        "year",
    ],
]

In [159]:
data = pd.concat([clean_waste_18_19, clean_waste_03_17]).sort_values(by="year")
data.head()

,recycling_rate,total_waste_generated_tonne,total_waste_recycled_tonne,waste_type,year
206,0.01,91600,900.0,Textile/Leather,2003
195,0.06,548000,32900.0,Food waste,2003
196,0.43,1084700,466200.0,Paper/Cardboard,2003
197,0.07,579900,39100.0,Plastics,2003
198,0.94,422900,398300.0,Construction Debris,2003

In [160]:
data['waste_type'].value_counts()

# Glass - Plastic - Ferrous Metal - Non-Ferrous Metal

Paper/Cardboard                            17
Textile/Leather                            17
Glass                                      17
Plastics                                   16
Total                                      15
Scrap Tyres                                13
Used Slag                                  13
Others (stones, ceramics & rubber etc)     12
Construction Debris                        11
Horticultural Waste                        11
Wood/Timber                                11
Non-ferrous Metals                         11
Sludge                                     11
Food waste                                 11
Ferrous Metal                               9
Food                                        6
Wood                                        6
Ash & Sludge                                5
Scrap tyres                                 4
Used slag                                   4
Ferrous Metals                              4
Horticultural waste                         4
Ferrous metal                               4
C&D                                         3
Non-ferrous metal                           3
Others (stones, ceramic, rubber, ect)       2
Construction& Demolition                    2
Horticultural                               2
Overall                                     2
Non-Ferrous Metal                           2
Others (stones, ceramics & rubber etc.)     1
Non-ferrous metals                          1
Others                                      1
Ash and sludge                              1
Plastic                                     1
Construction debris                         1
Others (stones, ceramic, rubber, etc.)      1
Name: waste_type, dtype: int64

In [161]:
data["waste_type"] = data["waste_type"].str.replace(
    "Plastics", "Plastic"
    )

data["waste_type"] = data["waste_type"].str.replace(
    "Paper/Cardboard", "Paper"
    )

data["waste_type"] = data["waste_type"].str.replace(
    "Ferrous Metals", "Ferrous Metal"
    )
data["waste_type"] = data["waste_type"].str.replace(
    "Ferrous metal", "Ferrous Metal"
    )

data["waste_type"] = data["waste_type"].str.replace(
    "Non-ferrous Metals", "Non-Ferrous Metal"
    )
data["waste_type"] = data["waste_type"].str.replace(
    "Non-ferrous metal", "Non-Ferrous Metal"
    )
data["waste_type"] = data["waste_type"].str.replace(
    "Non-ferrous metals", "Non-Ferrous Metal"
    )
data["waste_type"] = data["waste_type"].str.replace(
    "Non-Ferrous Metals", "Non-Ferrous Metal"
    )

data['waste_type'].value_counts()

Ferrous Metal                              17
Textile/Leather                            17
Non-Ferrous Metal                          17
Glass                                      17
Plastic                                    17
Paper                                      17
Total                                      15
Scrap Tyres                                13
Used Slag                                  13
Others (stones, ceramics & rubber etc)     12
Horticultural Waste                        11
Sludge                                     11
Food waste                                 11
Wood/Timber                                11
Construction Debris                        11
Wood                                        6
Food                                        6
Ash & Sludge                                5
Scrap tyres                                 4
Used slag                                   4
Horticultural waste                         4
C&D                                         3
Construction& Demolition                    2
Horticultural                               2
Overall                                     2
Others (stones, ceramic, rubber, ect)       2
Others (stones, ceramics & rubber etc.)     1
Others (stones, ceramic, rubber, etc.)      1
Others                                      1
Ash and sludge                              1
Construction debris                         1
Name: waste_type, dtype: int64

In [162]:
total_data = data.merge(
    clean_energy_saved, how="left", left_on="waste_type", right_on="material"
).dropna()

total_data["energy_saved"] = total_data["energy_saved"].str.replace("Kwh", "").astype(float)

total_data

,recycling_rate,total_waste_generated_tonne,total_waste_recycled_tonne,waste_type,year,material,energy_saved
3,0.07,579900,39100.0,Plastic,2003,Plastic,5774.0
7,0.93,856700,799000.0,Ferrous Metal,2003,Ferrous Metal,642.0
8,0.81,93900,75800.0,Non-Ferrous Metal,2003,Non-Ferrous Metal,14000.0
11,0.09,65500,6200.0,Glass,2003,Glass,42.0
17,0.83,86900,71800.0,Non-Ferrous Metal,2004,Non-Ferrous Metal,14000.0
21,0.11,683100,74100.0,Plastic,2004,Plastic,5774.0
25,0.90,720200,649900.0,Ferrous Metal,2004,Ferrous Metal,642.0
29,0.07,73600,4900.0,Glass,2004,Glass,42.0
31,0.13,674800,86000.0,Plastic,2005,Plastic,5774.0
36,0.06,62600,3800.0,Glass,2005,Glass,42.0
37,0.84,89400,74700.0,Non-Ferrous Metal,2005,Non-Ferrous Metal,14000.0
44,0.92,818300,749100.0,Ferrous Metal,2005,Ferrous Metal,642.0
47,0.12,656800,77800.0,Plastic,2006,Plastic,5774.0
51,0.91,725900,657400.0,Ferrous Metal,2006,Ferrous Metal,642.0
54,0.10,63000,6400.0,Glass,2006,Glass,42.0
59,0.82,86700,70700.0,Non-Ferrous Metal,2006,Non-Ferrous Metal,14000.0
63,0.11,659800,75000.0,Plastic,2007,Plastic,5774.0
67,0.82,92300,75600.0,Non-Ferrous Metal,2007,Non-Ferrous Metal,14000.0
70,0.09,65300,5800.0,Glass,2007,Glass,42.0
73,0.91,736500,668000.0,Ferrous Metal,2007,Ferrous Metal,642.0
77,0.09,684400,61200.0,Plastic,2008,Plastic,5774.0
81,0.94,784800,735000.0,Ferrous Metal,2008,Ferrous Metal,642.0
82,0.85,85000,72000.0,Non-Ferrous Metal,2008,Non-Ferrous Metal,14000.0
85,0.18,57100,10000.0,Glass,2008,Glass,42.0
92,0.09,688900,60300.0,Plastic,2009,Plastic,5774.0
96,0.21,73100,15600.0,Glass,2009,Glass,42.0
97,0.82,57600,47500.0,Non-Ferrous Metal,2009,Non-Ferrous Metal,14000.0
103,0.92,872000,806200.0,Ferrous Metal,2009,Ferrous Metal,642.0
105,0.11,740400,78100.0,Plastic,2010,Plastic,5774.0
109,0.94,1194600,1127500.0,Ferrous Metal,2010,Ferrous Metal,642.0
...,...,...,...,...,...,...,...
144,0.26,74900,19500.0,Glass,2012,Glass,42.0
149,0.79,122500,97300.0,Non-Ferrous Metal,2012,Non-Ferrous Metal,14000.0
153,0.11,832200,91100.0,Plastic,2013,Plastic,5774.0
157,0.84,135100,114000.0,Non-Ferrous Metal,2013,Non-Ferrous Metal,14000.0
160,0.20,73500,14600.0,Glass,2013,Glass,42.0
163,0.97,1416000,1369200.0,Ferrous Metal,2013,Ferrous Metal,642.0
170,0.09,869000,80000.0,Plastic,2014,Plastic,5774.0
172,0.80,118400,94700.0,Non-Ferrous Metal,2014,Non-Ferrous Metal,14000.0
175,0.96,1445900,1388900.0,Ferrous Metal,2014,Ferrous Metal,642.0
177,0.20,79500,15700.0,Glass,2014,Glass,42.0
182,0.07,824600,57800.0,Plastic,2015,Plastic,5774.0
185,0.99,1348500,1333300.0,Ferrous Metal,2015,Ferrous Metal,642.0
189,0.19,75200,14600.0,Glass,2015,Glass,42.0
194,0.89,180000,160400.0,Non-Ferrous Metal,2015,Non-Ferrous Metal,14000.0
197,0.07,822200,59500.0,Plastic,2016,Plastic,5774.0
202,0.99,97200,95900.0,Non-Ferrous Metal,2016,Non-Ferrous Metal,14000.0
203,0.99,1357500,1351500.0,Ferrous Metal,2016,Ferrous Metal,642.0
207,0.20,72300,14700.0,Glass,2016,Glass,42.0
211,0.99,1378800,1371000.0,Ferrous Metal,2017,Ferrous Metal,642.0
213,0.98,93700,92200.0,Non-Ferrous Metal,2017,Non-Ferrous Metal,14000.0
217,0.17,71300,12400.0,Glass,2017,Glass,42.0
220,0.06,815200,51800.0,Plastic,2017,Plastic,5774.0
227,0.10,1269000,126000.0,Ferrous Metal,2018,Ferrous Metal,642.0
229,0.04,949000,41000.0,Plastic,2018,Plastic,5774.0
235,0.99,171000,170000.0,Non-Ferrous Metal,2018,Non-Ferrous Metal,14000.0
236,0.19,64000,12000.0,Glass,2018,Glass,42.0
241,0.99,1278000,1270000.0,Ferrous Metal,2019,Ferrous Metal,642.0
243,0.04,930000,37000.0,Plastic,2019,Plastic,5774.0
249,0.98,126000,124000.0,Non-Ferrous Metal,2019,Non-Ferrous Metal,14000.0
250,0.15,75000,11000.0,Glass,2019,Glass,42.0

In [163]:
total_data["total_energy_saved"] = (
    total_data.loc[:, "total_waste_recycled_tonne"] * total_data.loc[:, "energy_saved"]
)

total_data.head()

,recycling_rate,total_waste_generated_tonne,total_waste_recycled_tonne,waste_type,year,material,energy_saved,total_energy_saved
3,0.07,579900,39100.0,Plastic,2003,Plastic,5774.0,2.257634e+08
7,0.93,856700,799000.0,Ferrous Metal,2003,Ferrous Metal,642.0,5.129580e+08
8,0.81,93900,75800.0,Non-Ferrous Metal,2003,Non-Ferrous Metal,14000.0,1.061200e+09
11,0.09,65500,6200.0,Glass,2003,Glass,42.0,2.604000e+05
17,0.83,86900,71800.0,Non-Ferrous Metal,2004,Non-Ferrous Metal,14000.0,1.005200e+09

In [164]:
annual_energy_savings = pd.DataFrame(
    total_data.groupby(by=["year"]).sum()["total_energy_saved"],
    columns=["total_energy_saved"],
    ).astype({"total_energy_saved": float})

# annual_energy_savings["total_energy_saved"] = annual_energy_savings["total_energy_saved"].astype(str) + " kWh"

annual_energy_savings = annual_energy_savings.tail() 

annual_energy_savings

      total_energy_saved
year
2015        3.435929e+09
2016        2.554433e+09
2017        2.470596e+09
2018        2.698130e+09
2019        2.765440e+09